import { type IGitPlatformProvider, type GitPlatformPullRequest } from "./IGitPlatformProvider.js";
import { MonorepoBuildGate } from "./MonorepoBuildGate.js";
import { PromotionSanitizer } from "./PromotionSanitizer.js";
import { ReleaseBundlerService, type ReleaseTaskItem, type MilestoneReleaseBundle } from "./ReleaseBundlerService.js";
import { SandboxedProcessRunner } from "../testing/SandboxedProcessRunner.js";

export interface GitHubPromotionPipelineConfig {
  readonly gitPlatformProvider: IGitPlatformProvider;
  readonly repoOwner?: string | undefined;
  readonly repoName?: string | undefined;
  readonly baseBranch?: string | undefined;
  readonly gitRemote?: string | undefined;
  readonly buildGate?: MonorepoBuildGate | undefined;
  readonly sanitizer?: PromotionSanitizer | undefined;
  readonly bundler?: ReleaseBundlerService | undefined;
  readonly runner?: SandboxedProcessRunner | undefined;
}

export interface PromoteMilestoneOptions {
  readonly releaseBranch: string;
  readonly milestoneTitle: string;
  readonly changelog: string;
  readonly workspacePath?: string | undefined;
  readonly dryRun?: boolean | undefined;
  readonly baseBranch?: string | undefined;
  readonly owner?: string | undefined;
  readonly repo?: string | undefined;
  readonly gitRemote?: string | undefined;
  readonly diff?: string | undefined;
  readonly filePaths?: readonly string[] | undefined;
}

export interface PromotionResult {
  readonly success: boolean;
  readonly dryRun: boolean;
  readonly releaseBranch: string;
  readonly pullRequest?: GitPlatformPullRequest | undefined;
  readonly quarantinePassed: boolean;
  readonly changelog: string;
  readonly error?: string | undefined;
}

export class GitHubPromotionPipeline {
  private readonly provider: IGitPlatformProvider;
  private readonly owner: string;
  private readonly repo: string;
  private readonly defaultBaseBranch: string;
  private readonly defaultRemote: string;
  private readonly buildGate: MonorepoBuildGate;
  private readonly sanitizer: PromotionSanitizer;
  private readonly bundler: ReleaseBundlerService;
  private readonly runner: SandboxedProcessRunner;

  constructor(config: GitHubPromotionPipelineConfig) {
    this.provider = config.gitPlatformProvider;
    this.owner = config.repoOwner || process.env.GITHUB_OWNER || "Brennername";
    this.repo = config.repoName || process.env.GITHUB_REPO || "cacophony";
    this.defaultBaseBranch = config.baseBranch || "main";
    this.defaultRemote = config.gitRemote || "origin";
    this.buildGate = config.buildGate ?? new MonorepoBuildGate();
    this.sanitizer = config.sanitizer ?? new PromotionSanitizer();
    this.bundler = config.bundler ?? new ReleaseBundlerService();
    this.runner = config.runner ?? new SandboxedProcessRunner();
  }

  public async runQuarantineGauntlet(options: {
    workspacePath?: string | undefined;
    diff?: string | undefined;
    filePaths?: readonly string[] | undefined;
  }): Promise<{ passed: boolean; error?: string | undefined }> {
    if (options.workspacePath) {
      const buildResult = await this.buildGate.verifyBuild(options.workspacePath);
      if (!buildResult.passed) {
        return {
          passed: false,
          error: buildResult.failureSummary || "Monorepo build verification failed"
        };
      }
    }

    if (options.diff || options.filePaths) {
      const sanitization = this.sanitizer.sanitize({
        diff: options.diff,
        filePaths: options.filePaths
      });
      if (!sanitization.passed) {
        return {
          passed: false,
          error: sanitization.summary
        };
      }
    }

    return { passed: true };
  }

  public async promoteMilestoneToGitHub(options: PromoteMilestoneOptions): Promise<PromotionResult> {
    const owner = options.owner || this.owner;
    const repo = options.repo || this.repo;
    const baseBranch = options.baseBranch || this.defaultBaseBranch;
    const remote = options.gitRemote || this.defaultRemote;
    const dryRun = options.dryRun ?? false;

    const gauntlet = await this.runQuarantineGauntlet({
      workspacePath: options.workspacePath,
      diff: options.diff,
      filePaths: options.filePaths
    });

    if (!gauntlet.passed) {
      return {
        success: false,
        dryRun,
        releaseBranch: options.releaseBranch,
        quarantinePassed: false,
        changelog: options.changelog,
        error: gauntlet.error
      };
    }

    const prBody = [
      "## Cacophony Milestone Release Promotion",
      "",
      `**Milestone:** ${options.milestoneTitle}`,
      `**Release Branch:** \`${options.releaseBranch}\``,
      "",
      "[![Cacophony Verification](https://img.shields.io/badge/Cacophony_Verification-100%25_Passed-success)](#)",
      "[![SOLID Compliance](https://img.shields.io/badge/SOLID_Compliance-Strict-blue)](#)",
      "",
      options.changelog,
      "",
      "---",
      "*Automated milestone promotion generated by Cacophony Engine Quarantine Gauntlet.*"
    ].join("\n");

    if (dryRun) {
      return {
        success: true,
        dryRun: true,
        releaseBranch: options.releaseBranch,
        quarantinePassed: true,
        changelog: options.changelog
      };
    }

    if (!/^[a-zA-Z0-9_.\-\/]+$/.test(remote) || !/^[a-zA-Z0-9_.\-\/]+$/.test(options.releaseBranch)) {
      throw new Error("Invalid git ref format for push command");
    }

    const pushCmd = `git push ${remote} ${options.releaseBranch}:${options.releaseBranch}`;
    const pushResult = await this.runner.run(pushCmd, {
      cwd: options.workspacePath || process.cwd(),
      timeoutMs: 60000
    });

    if (pushResult.exitCode !== 0) {
      return {
        success: false,
        dryRun: false,
        releaseBranch: options.releaseBranch,
        quarantinePassed: true,
        changelog: options.changelog,
        error: `Git push failed: ${(pushResult.stderr || pushResult.stdout).slice(0, 400)}`
      };
    }

    try {
      const pr = await this.provider.openPullRequest(owner, repo, {
        title: `[Milestone Release] ${options.milestoneTitle}`,
        body: prBody,
        head: options.releaseBranch,
        base: baseBranch
      });

      return {
        success: true,
        dryRun: false,
        releaseBranch: options.releaseBranch,
        pullRequest: pr,
        quarantinePassed: true,
        changelog: options.changelog
      };
    } catch (prErr) {
      return {
        success: false,
        dryRun: false,
        releaseBranch: options.releaseBranch,
        quarantinePassed: true,
        changelog: options.changelog,
        error: `Failed to open GitHub Pull Request: ${prErr instanceof Error ? prErr.message : String(prErr)}`
      };
    }
  }

  public async bundleAndPromote(options: {
    milestoneTitle: string;
    previousVersion: string;
    tasks: readonly ReleaseTaskItem[];
    workspacePath?: string | undefined;
    dryRun?: boolean | undefined;
    baseBranch?: string | undefined;
  }): Promise<{ bundle: MilestoneReleaseBundle; result: PromotionResult }> {
    const bundle = this.bundler.bundleMilestone({
      milestoneTitle: options.milestoneTitle,
      previousVersion: options.previousVersion,
      tasks: options.tasks
    });

    const result = await this.promoteMilestoneToGitHub({
      releaseBranch: bundle.releaseBranch,
      milestoneTitle: options.milestoneTitle,
      changelog: bundle.changelog,
      workspacePath: options.workspacePath,
      dryRun: options.dryRun,
      baseBranch: options.baseBranch
    });

    return { bundle, result };
  }
}
