import {
  HardwareDiscoveryReport,
  WhiteboxOverrideConfig,
} from "@cacophony/shared-types";

/**
 * OllamaSystemdGenerator
 *
 * Generates drop-in systemd configurations and kernel modprobe files
 * tailored to detected compute architectures (specifically AMD Vega APU vs RDNA vs CUDA).
 */
export class OllamaSystemdGenerator {
  /**
   * Generates whitebox override files for the system.
   */
  public generate(report: HardwareDiscoveryReport): WhiteboxOverrideConfig {
    const isVegaApu = report.primaryCategory === "AMD_APU_VEGA";
    const isCuda = report.primaryCategory === "NVIDIA_CUDA";
    const isRdna = report.primaryCategory === "AMD_DISCRETE_RDNA";

    let envVars: Record<string, string> = {
      OLLAMA_HOST: "0.0.0.0:11434",
      OLLAMA_KEEP_ALIVE: "-1",
      OLLAMA_DEBUG: "1",
    };

    let modprobePath: string | undefined;
    let modprobeContent: string | undefined;

    if (isVegaApu) {
      envVars = {
        ...envVars,
        OLLAMA_IGPU_ENABLE: "1",
        OLLAMA_VULKAN: "1",
        OLLAMA_FLASH_ATTENTION: "0",
        OLLAMA_NUM_PARALLEL: "1",
        OLLAMA_MAX_LOADED_MODELS: "1",
      };

      modprobePath = "/etc/modprobe.d/amdgpu.conf";
      modprobeContent = `# Cacophony Vega APU Hardening Configuration
# Extends GPU compute ring watchdog timeout to prevent resets during long prompt evaluations
options amdgpu lockup_timeout=120000
options amdgpu vm_update_mode=0
`;
    } else if (isRdna) {
      envVars = {
        ...envVars,
        HSA_OVERRIDE_GFX_VERSION: "10.3.0",
        OLLAMA_FLASH_ATTENTION: "1",
        OLLAMA_NUM_PARALLEL: "2",
        OLLAMA_MAX_LOADED_MODELS: "2",
      };
    } else if (isCuda) {
      envVars = {
        ...envVars,
        CUDA_VISIBLE_DEVICES: "0",
        OLLAMA_FLASH_ATTENTION: "1",
        OLLAMA_NUM_PARALLEL: "2",
        OLLAMA_MAX_LOADED_MODELS: "3",
      };
    } else {
      // CPU fallback
      envVars = {
        ...envVars,
        OLLAMA_NUM_THREADS: "8",
        OLLAMA_NUM_PARALLEL: "1",
        OLLAMA_MAX_LOADED_MODELS: "1",
      };
    }

    const systemdOverridePath = "/etc/systemd/system/ollama.service.d/override.conf";
    const systemdOverrideContent = this.formatSystemdOverride(envVars);

    return {
      profileId: report.recommendedProfileId,
      systemdOverridePath,
      systemdOverrideContent,
      ...(modprobePath ? { modprobePath } : {}),
      ...(modprobeContent ? { modprobeContent } : {}),
      environmentVars: envVars,
    };
  }

  private formatSystemdOverride(envVars: Record<string, string>): string {
    const lines = [
      `### Generated by Cacophony Whitebox Ollama Tuning Engine`,
      `### Target Architecture: Auto-Calibrated`,
      `[Service]`,
    ];

    for (const [k, v] of Object.entries(envVars)) {
      lines.push(`Environment="${k}=${v}"`);
    }

    lines.push("");
    return lines.join("\n");
  }
}
